export const DISTRICT_NAMES: Record<number, string> = {
  1:  "Raffles Place / Marina",
  2:  "Tanjong Pagar",
  3:  "Queenstown / Bukit Merah",
  4:  "Harbourfront / Sentosa",
  5:  "Buona Vista / Clementi",
  6:  "City Hall / Clarke Quay",
  7:  "Beach Road / Bugis",
  9:  "Orchard / River Valley",
  10: "Bukit Timah / Holland",
  11: "Novena / Thomson",
  12: "Toa Payoh / Balestier",
  14: "Geylang / Eunos",
  15: "Katong / Joo Chiat",
  16: "Bedok",
  17: "Changi / Loyang",
  18: "Tampines / Pasir Ris",
  19: "Hougang / Sengkang / Punggol",
  20: "Ang Mo Kio / Bishan",
  21: "Bukit Panjang / Hillview",
  22: "Jurong / Boon Lay",
  23: "Choa Chu Kang / Bukit Batok",
  24: "Lim Chu Kang / Tengah",
  25: "Woodlands / Kranji",
  26: "Mandai / Upper Thomson",
  27: "Yishun / Sembawang",
  28: "Seletar",
};
